sudo: required
services:
- docker
language: bash

script:
# Set up qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# Build the container
- docker build -t beckonconn/fluentd-docker-arm:build .
# Test for container architecture
- docker run -it --rm beckonconn/fluentd-docker-arm:build uname -a
